const {createClient}=supabase; const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY); let session=null;
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('login').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('auth-msg').textContent=error.message;return}session=data.session;await start();});
$('logout').addEventListener('click',()=>db.auth.signOut()); $('reset').addEventListener('click',clearForm);
$('article-form').addEventListener('submit',async e=>{e.preventDefault(); if(!session)return; const payload={title:$('title').value,slug:$('slug').value,subtitle:$('subtitle').value,excerpt:$('excerpt').value,category:$('category').value,cover_image_url:$('cover').value||null,status:$('status').value,content_html:$('content').value,author_name:'Emmanuel Odeleye',published_at:$('status').value==='published'?new Date().toISOString():null}; const id=$('article-id').value; const q=id?db.from('articles').update(payload).eq('id',id):db.from('articles').insert(payload); const {error}=await q; $('save-msg').textContent=error?error.message:'Saved successfully.'; if(!error){clearForm();loadArticles();}});
async function start(){const {data:u}=await db.auth.getUser(); $('auth').hidden=true; $('dashboard').hidden=false; $('userline').textContent=u.user.email; loadArticles();loadComments();}
async function loadArticles(){const {data,error}=await db.from('articles').select('*').order('created_at',{ascending:false}); if(error){$('articles').innerHTML='<p>'+esc(error.message)+'</p>';return} $('articles').innerHTML=data.length?data.map(a=>`<div class="admin-row"><div><b>${esc(a.title)}</b><br><span class="date">${esc(a.category)} · ${esc(a.status)}</span></div><div><span class="status">${esc(a.status)}</span><button onclick="editArticle('${a.id}')">EDIT</button>${a.status==='published'?`<a href="article.html?slug=${encodeURIComponent(a.slug)}" target="_blank">VIEW</a>`:''}<button class="danger" onclick="deleteArticle('${a.id}')">DELETE</button></div></div>`).join(''):'<p>No publications yet.</p>';}
window.editArticle=async id=>{const {data}=await db.from('articles').select('*').eq('id',id).single(); if(!data)return; $('article-id').value=data.id;$('title').value=data.title;$('slug').value=data.slug;$('subtitle').value=data.subtitle||'';$('excerpt').value=data.excerpt||'';$('category').value=data.category;$('cover').value=data.cover_image_url||'';$('status').value=data.status;$('content').value=data.content_html;$('editor-title').textContent='Edit publication';window.scrollTo({top:0,behavior:'smooth'});};
window.deleteArticle=async id=>{if(!confirm('Delete this publication?'))return;await db.from('articles').delete().eq('id',id);loadArticles();};
async function loadComments(){const {data,error}=await db.from('comments').select('id,name,body,image_url,created_at,approved,article_id,articles(title)').order('created_at',{ascending:false}); if(error){$('comments').innerHTML='<p>'+esc(error.message)+'</p>';return} $('comments').innerHTML=data.length?data.map(c=>`<div class="admin-row"><div><b>${esc(c.name)}</b> <span class="date">${c.approved?'APPROVED':'PENDING'}</span><br><span class="date">${esc(c.articles?.title||'')}</span><p>${esc(c.body)}</p>${c.image_url?`<img class="admin-comment-image" src="${esc(c.image_url)}" alt="">`:''}</div><div>${!c.approved?`<button onclick="approveComment('${c.id}')">APPROVE</button>`:''}<button class="danger" onclick="deleteComment('${c.id}')">DELETE</button></div></div>`).join(''):'<p>No comments.</p>';}
window.approveComment=async id=>{await db.from('comments').update({approved:true}).eq('id',id);loadComments();}; window.deleteComment=async id=>{if(!confirm('Delete comment?'))return;await db.from('comments').delete().eq('id',id);loadComments();};
function clearForm(){$('article-id').value='';$('title').value='';$('slug').value='';$('subtitle').value='';$('excerpt').value='';$('cover').value='';$('content').value='';$('status').value='draft';$('editor-title').textContent='New publication';$('save-msg').textContent='';}
db.auth.getSession().then(({data})=>{if(data.session){session=data.session;start();}}); db.auth.onAuthStateChange((_e,s)=>{session=s;if(!s){$('auth').hidden=false;$('dashboard').hidden=true;}});
